### ISSUE TITLE
jupyter notebook cannot be loaded

### ISSUE THREAD

**Issue by Wenduokcl** [ttgump/scDeepCluster#1]
Hi, 

Could you check and see whether the jupyter noebook is working fine? I tried to open it with different laptops and on none of  them could get jupyter notebook loaded.

Thanks a lot.

**Comment by ttgump** [comment]
Hi,
I tried on Chrome and Safari, both work fine. What system and browser you are using? Thanks.

**Comment by wendy-yy** [comment]
It is working now, not sure what was wrong. Thank you for your response>-<
