### ISSUE TITLE
ImportError: cannot import name 'extension_dict'

### ISSUE THREAD

**Issue by wyj045000** [ttgump/scDeepCluster#5]
Hello, I set up the environment according to your installation requirements, but it has not been successful. I encountered the following problems.
![image](https://user-images.githubusercontent.com/39802240/71942811-650a1a00-31f9-11ea-981b-c2792bf6aba5.png)

**Comment by ttgump** [comment]
It seems this is a issue of the Keras or tensorflow. I would suggest you to reinstall tensorflow and Keras again.
