### ISSUE TITLE
repeat results

### ISSUE THREAD

**Issue by cquzys** [ttgump/scDeepCluster#6]
Hi  Tian Tian:

   I read the paper "Clustering single-cell RNA-seq data with a model-based deep learning approach"   on nature machine intelligence, I can not repeat a few results in your paper, such as the result of Mouse ES cells dataset on Fig.3 in the paper, the CA, NMI and ARI is 0.98, 0.97, 0.97 in the paper, but I repeat is ACC: 0.7674, NMI: 0.6714, ARI: 0.5398.
In another hand, for the splatter dataset, the CA and ARI are 0.75, 0.55 when setting sigma to 0.2 in Supplementary Figure 3. The results I repeat are 0.4420 and 0.0390. so, maybe I need to set some parameters but I ignored, can you give me some suggestions? Thank you!

best wishes

**Comment by ttgump** [comment]
Use the same version of tensorflow and keras as I stated in the Readme. Thanks.
Best,
Tian
