### ISSUE TITLE
scDeepCluster in HPC

### ISSUE THREAD

**Issue by Shicheng-Guo** [ttgump/scDeepCluster#7]
Hi Tiantain, 

Is scDeepCluster available for HPC for example SDSC or TACC? 

Thanks. 

Shicheng

**Comment by ttgump** [comment]
> Hi Tiantain,
> 
> Is scDeepCluster available for HPC for example SDSC or TACC?
> 
> Thanks.
> 
> Shicheng

I am not sure I understand the question correctly, but you can install the dependent packages by conda or pip and then download the source code of scDeepCluster in the HPCs. Are you asking if scDeepCluster available in a package that can be used for HPC by immediate downloading?
Best,
Tian
