### ISSUE TITLE
how can I get clustering information of every cell?

### ISSUE THREAD

**Issue by hytzuikeai** [ttgump/scDeepCluster#8]
hi, I 've downloaded and repeated your code successfully, then I got three clustering results called NMI,CA and ARI.but how can I find clustering information of every cell such as `Fig. 3: Benchmark results on four real scRNA-seq datasets with true labels-b`
[fig](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs42256-019-0037-0/MediaObjects/42256_2019_37_Fig3_HTML.png?as=webp)

**Comment by ttgump** [comment]
Hi,
In the end of scDeepCluster.py script, the line 401 
`y_pred = scDeepCluster.y_pred`
You can just output and save the y_pred to a file you want, such as
`np.savetxt("pred_y.txt", y_pred, delimiter=",", fmt="%I")`

You can also check my pytorch implementation, where I add an argument setting file name to store the predict labels. Check:
https://github.com/ttgump/scDeepCluster_pytorch

Best,
Tian

**Comment by ttgump** [comment]
> hi, I 've downloaded and repeated your code successfully, then I got three clustering results called NMI,CA and ARI.but how can I find clustering information of every cell such as `Fig. 3: Benchmark results on four real scRNA-seq datasets with true labels-b`
> [fig](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs42256-019-0037-0/MediaObjects/42256_2019_37_Fig3_HTML.png?as=webp)

Hi,
In the end of scDeepCluster.py script, the line 401 
`y_pred = scDeepCluster.y_pred`
You can just output and save the y_pred to a file you want, such as
`np.savetxt("pred_y.txt", y_pred, delimiter=",", fmt="%I")`

You can also check my pytorch implementation, where I add an argument setting file name to store the predict labels. Check:
https://github.com/ttgump/scDeepCluster_pytorch

Best,
Tian
